# Generated by Django 2.2.7 on 2020-03-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releaseapk',
            old_name='data',
            new_name='date',
        ),
    ]
