# Generated by Django 2.2.7 on 2020-01-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaseapk',
            name='user',
        ),
        migrations.AddField(
            model_name='releaseapk',
            name='email_field',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
