# Generated by Django 3.0.4 on 2020-04-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key_table',
            name='key_pass',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keystore_table',
            name='keystore_pass',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
