# Generated by Django 2.2.7 on 2020-01-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='debugapk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=2048)),
            ],
        ),
        migrations.RenameModel(
            old_name='apk',
            new_name='releaseapk',
        ),
    ]
