# Generated by Django 3.0.4 on 2020-04-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200404_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystore_table',
            name='keystore',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
