# Generated by Django 2.2.7 on 2020-03-14 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200304_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystore_table',
            name='keystore',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keystore_table',
            name='keystore_link',
            field=models.CharField(default='/dashboard/', max_length=120),
        ),
        migrations.AlterField(
            model_name='keystore_table',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='releaseapk',
            name='domain_name',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
