# Generated by Django 2.2.7 on 2020-02-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200225_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaseapk',
            name='email_field',
        ),
        migrations.AddField(
            model_name='releaseapk',
            name='keystore',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
