# Generated by Django 2.2.7 on 2020-03-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200225_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseapk',
            name='keystore_link',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
