# Generated by Django 3.0.4 on 2020-04-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200405_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystore_table',
            name='domain_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
