# Generated by Django 2.2.7 on 2020-03-14 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200314_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key_table',
            name='key',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='keystore_table',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
