# Generated by Django 3.0.4 on 2020-04-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_keystore_table_domain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keystore_table',
            old_name='domain_name',
            new_name='app_name',
        ),
    ]
