# Generated by Django 2.2.7 on 2020-03-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_releaseapk_keystore_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseapk',
            name='keystore_link',
            field=models.CharField(blank=True, default='dashboard/', max_length=120, unique=True),
        ),
    ]
