# Generated by Django 2.2.7 on 2020-03-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200314_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseapk',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='releaseapk',
            name='domain_name',
            field=models.CharField(max_length=2048),
        ),
    ]
