# Generated by Django 3.0.4 on 2020-04-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200418_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_and_keystore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keystore', models.CharField(max_length=120)),
                ('app_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='keystore_table',
            name='app_name',
        ),
    ]
