# Generated by Django 3.0.4 on 2020-03-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200315_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keystore', models.CharField(max_length=120)),
                ('key', models.CharField(max_length=120)),
            ],
        ),
    ]
