# Generated by Django 2.2.7 on 2020-03-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200301_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseapk',
            name='app_name',
            field=models.CharField(default='app', max_length=120),
        ),
        migrations.AlterField(
            model_name='releaseapk',
            name='keystore_link',
            field=models.CharField(blank=True, default='/dashboard/', max_length=120, unique=True),
        ),
    ]
