# Generated by Django 2.2.7 on 2020-03-02 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200301_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='keystore_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keystore', models.CharField(max_length=100, unique=True)),
                ('keystore_link', models.CharField(default='/dashboard/', max_length=120, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
