# Generated by Django 3.0.4 on 2020-04-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200419_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystore_table',
            name='keystore',
            field=models.CharField(max_length=100),
        ),
    ]
