# Generated by Django 3.0.4 on 2020-03-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_temp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='user',
        ),
    ]
