# Generated by Django 2.2.7 on 2020-03-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_keystore_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystore_table',
            name='key',
            field=models.CharField(blank=True, max_length=2048, unique=True),
        ),
    ]
