# Generated by Django 2.2.7 on 2020-03-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_keystore_table_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystore_table',
            name='key',
            field=models.CharField(max_length=2048, unique=True),
        ),
    ]
