# Generated by Django 2.2.7 on 2020-03-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200302_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaseapk',
            name='key',
        ),
        migrations.RemoveField(
            model_name='releaseapk',
            name='keystore',
        ),
        migrations.RemoveField(
            model_name='releaseapk',
            name='keystore_link',
        ),
    ]
