# Generated by Django 2.2.7 on 2020-03-02 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200302_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keystore_table',
            name='key',
        ),
        migrations.CreateModel(
            name='key_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2048, unique=True)),
                ('keystore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.keystore_table')),
            ],
        ),
    ]
