# Generated by Django 3.0.4 on 2020-03-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200324_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='user',
        ),
    ]
